parameters:
- name: command
  type: string
  default: ping
- name: konnect_runtime_group
  type: string
  default: "default"
- name: konnect_service_name
  type: string
  default: ""
- name: options
  type: string

steps:  
- script: |
    sudo apt-get install -y python-jinja2
    sudo pip3 install PyYAML
  condition: ne('${{ parameters.command }}', 'ping')
- task: PythonScript@0
  condition: and(succeeded(), ne('${{ parameters.command }}', 'ping'))
  inputs:
    scriptSource: 'filePath'
    scriptPath: $(System.DefaultWorkingDirectory)/generate_yaml.py
  env:
    KONNECT_SERVICE_NAME: ${{ parameters.konnect_service_name }}
    KONNECT_RUNTIME_GROUP: ${{ parameters.konnect_runtime_group }}
- script: |
    docker run -v "$(System.DefaultWorkingDirectory)/results":/tmp/deck --rm kong/deck:v1.15.1 ${{ parameters.command }} --konnect-runtime-group-name ${{ parameters.konnect_runtime_group }} ${{ parameters.options }} --tls-skip-verify
  condition: succeeded()