parameters:
- name: command
  type: string
  default: ping
- name: kong_workspaces
  type: string
  default: kong
- name: options
  type: string
  
jobs:
- job: deckAction
  displayName: Deck Action
  steps:
  - task: Docker@2
    displayName: Build
    inputs:
      command: build
      containerRegistry: APD Registry
      repository: kong-deck
      dockerFile: dockerfile
      tags: latest
      arguments: 
      
  - task: Docker@2
    displayName: Push
    inputs:
      command: push
      containerRegistry: APD Registry
      repository: kong-deck
      tags: latest
  
  - task: Docker@2
    displayName: Docker Run deck
  - script: |
      docker run registry.dev.apdcomms.co.uk:443/kong-deck:latest 