parameters:
- name: command
  type: string
  default: ping
- name: kong_workspaces
  type: string
  default: kong
- name: options
  type: string
  
jobs:
- job: deckAction
  displayName: Deck Action
  steps:
  - task: Docker@2
    displayName: Login
    inputs:
      containerRegistry: 'MyDockerHub'
      command: 'login'  
  
  - task: Docker@2
    displayName: Build
    inputs:
      containerRegistry: 'MyDockerHub'
      repository: 'test-deck'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
  
  - task: Docker@2
    displayName: Docker Run deck
  - script: |
      docker run https://hub.docker.com/test-deck/deck:latest 