parameters:
- name: command
  type: string
  default: ping
- name: kong_workspaces
  type: string
  default: kong
- name: options
  type: string
- name: env
  type: string
  default: test
  
steps:  
- task: Docker@2
  displayName: Docker Run deck
- script: |
    docker run pjanicked/test-deck ${{ parameters.command }} ${{ parameters.kong_workspaces }} ${{ parameters.options }} ${{ parameters.env }}