parameters:
- name: command
  type: string
  default: ping
- name: kong_workspaces
  type: string
  default: kong
- name: options
  type: string
  
jobs:
- job: deckAction
  displayName: Deck Actions
  steps:  
  - task: Docker@2
    displayName: Build and Push docker image
    inputs:
      containerRegistry: 'MyDockerHub'
      repository: 'pjanicked/test-deck'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: latest
  
  - task: Docker@2
    displayName: Docker Run deck
  - script: |
      docker run pjanicked/test-deck