pr:
- master

resources:
- repo: self

variables:
  - group: 'kong-demo'

stages:
# - stage: build_and_push_docker_image
#   displayName: Build and push deck docker image
#   jobs:
#   - job: build_docker_image
#     displayName: Build and push docker
#     steps:  
#     - task: Docker@2
#       displayName: Build and Push docker image
#       inputs:
#         containerRegistry: 'MyDockerHub'
#         repository: 'pjanicked/test-deck'
#         command: 'buildAndPush'
#         Dockerfile: '**/Dockerfile'
#         tags: latest  

- stage: deck_dev
  displayName: Deck Test Environment
  # condition: and(or(eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'BatchedCI'), eq(variables['Build.Reason'], 'Manual')), succeeded())
  # dependsOn: build_and_push_docker_image
  jobs:
  - template: /deck_commands.yaml
    parameters:
      kong_url: https://us.api.konghq.com
      kong_file: dev.yaml
      kong_runtime_group: dev
      konnect_token: $(konnect-token)
      
- stage: deck_master
  displayName: Deck Master Environment
  condition: and(or(eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'BatchedCI'), eq(variables['Build.Reason'], 'Manual')), succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  dependsOn: deck_dev
  jobs:
  - template: /deck_commands.yaml
    parameters:
      kong_url: https://us.api.konghq.com
      kong_file: master.yaml
      kong_runtime_group: default
      konnect_token: $(konnect-token)