trigger:
- master

resources:
- repo: self

stages:
- stage: BuildAndPushDockerImage
  displayName: Build and push deck docker image
  jobs:
  - job: deckAction
    displayName: Build and push docker
    steps:  
    - task: Docker@2
      displayName: Build and Push docker image
      inputs:
        containerRegistry: 'MyDockerHub'
        repository: 'pjanicked/test-deck'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: latest  
      
- stage: Deck_Ping
  displayName: Deck Ping for Kong
  jobs:
  - template: /action.yaml
    parameters:
      command: ping
      options: kong-addr https://heroku-kong-pjanicked.herokuapp.com/kong-admin
      
- stage: Deck_Validate
  displayName: Deck Validate for Kong
  jobs:
  - template: /action.yaml
    parameters:
      command: validate
      options: kong-addr https://heroku-kong-pjanicked.herokuapp.com/kong-admin
      kong_workspaces: kong
      
- stage: Deck_Sync
  displayName: Deck Sync for Kong
  jobs:
  - template: /action.yaml
    parameters:
      command: sync
      options: kong-addr https://heroku-kong-pjanicked.herokuapp.com/kong-admin
      kong_workspaces: kong