parameters:
- name: kong_url
  type: string
  default: https://us.api.konghq.com
- name: to_sync
  type: boolean
  default: false
- name: kong_file
  type: string
  default: dev.yaml
- name: kong_runtime_group
  type: string
  default: dev

variables:
  - group: kong-demo

jobs:
- job: Deck_Ping
  displayName: Deck Ping for Kong
  steps:
    - template: /action.yaml
      parameters:
        command: ping
        options: "--konnect-token $(konnect-token)"
        
- job: Deck_Validate
  displayName: Deck Validate for Kong
  dependsOn: Deck_Ping
  steps:
    - template: /action.yaml
      parameters:
        command: validate
        options: "--konnect-token $(konnect-token)"
        kong_runtime_group: "--konnect-runtime-group-name ${{ parameters.kong_runtime_group }}"
        kong_file: ${{ parameters.kong_file }}

- ${{ if eq(parameters.to_sync, false) }}:       
  - job: Deck_Diff
    displayName: Deck Diff for Kong
    dependsOn:
    - Deck_Ping
    - Deck_Validate
    steps:
      - template: /action.yaml
        parameters:
          command: diff
          options: "--konnect-token $(konnect-token)"
          kong_runtime_group: "--konnect-runtime-group-name ${{ parameters.kong_runtime_group }}"
          kong_file: ${{ parameters.kong_file }}

- ${{ if eq(parameters.to_sync, true) }}:      
  - job: Deck_Sync
    displayName: Deck Sync for Kong
    dependsOn:
    - Deck_Ping
    - Deck_Validate
    steps:
      - template: /action.yaml
        parameters:
          command: sync
          options: "--konnect-token $(konnect-token)"
          kong_runtime_group: "--konnect-runtime-group-name ${{ parameters.kong_runtime_group }}"
          kong_file: ${{ parameters.kong_file }}